### ISSUE TITLE
node version update 12.16.1 -> 12.16.2 causes error for "icu4c-data"

### ISSUE THREAD

**Issue by vincentschroeder** [unicode-org/full-icu-npm#48]
After updating LTS node version I get the following errors when installing dependencies:
```
Arguments: 
Directory: /node_modules/full-icu
Output:
npm install icu4c-data@65l (Node 12.16.2 and small-icu 65.1) -> icudt65l.dat
Looks like you are using yarn…
full-icu$ .nvm/versions/node/v12.16.2/bin/node .nvm/versions/node/v12.16.1/lib/node_modules/yarn/bin/yarn.js add icu4c-data@65l --no-lockfile --ignore-scripts
yarn add v1.22.4
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find any versions for "icu4c-data" that matches "65l"
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
/node_modules/full-icu/install-spawn.js:41
                throw(Error(cmdPath + ' ' + args.join(' ') + ' --> status ' + spawned.status));
                ^

Error: .nvm/versions/node/v12.16.2/bin/node .nvm/versions/node/v12.16.1/lib/node_modules/yarn/bin/yarn.js add icu4c-data@65l --no-lockfile --ignore-scripts --> status 1
    at npmInstallNpm (/node_modules/full-icu/install-spawn.js:41:9)
    at Object.<anonymous> (/node_modules/full-icu/postinstall.js:72:2)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)```

**Comment by ex1st** [comment]
Duplicate #46
