### ISSUE TITLE
Broken url.parse

### ISSUE THREAD

**Issue by DimitryDushkin** [unicode-org/full-icu-npm#8]
I've started getting error on:

```
NODE_ICU_DATA=node_modules/full-icu node
> var url = require('url');
> url.parse('http://artemredkin.dev.ydf.yandex.net:9010/index');

Error: Cannot convert name to ASCII
    at Error (native)
    at Url.parse (url.js:320:23)
    at Object.urlParse [as parse] (url.js:81:5)
    at repl:1:5
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
    at REPLServer.defaultEval (repl.js:313:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
```

If `NODE_ICU_DATA` is not set everything is fine.

node v6.9.1, ubuntu 14.04.05

**Comment by awolden** [comment]
I had a similar issue, but it turned out that the CI system was bundling the package using node version 6.5 and the app was running on 6.10. The difference in node versions was causing the incorrect icudata file to be downloaded.

**Comment by srl295** [comment]
@DimitryDushkin sorry for a year late response, but yes you need to run the `npm install` and execution environment from the same node version as @awolden mentioned.

**Comment by DimitryDushkin** [comment]
Probably that was the case. Thank you.
